INSERT INTO customers (rank, company_name, revenue, country, address, industry) VALUES
(1, 'Walmart', 559151, 'United States', 'Bentonville, AR', 'Retailing'),
(2, 'Amazon.com', 386064, 'United States', 'Seattle, WA', 'Internet Services and Retailing'),
(3, 'Exxon Mobil', 264938, 'United States', 'Irving, TX', 'Energy'),
(4, 'Berkshire Hathaway', 254616, 'United States', 'Omaha, NE', 'Financials'),
(5, 'Apple', 253759, 'United States', 'Cupertino, CA', 'Technology'),
(6, 'UnitedHealth Group', 242155, 'United States', 'Minnetonka, MN', 'Health Care'),
(7, 'McKesson', 229660, 'United States', 'Irving, TX', 'Wholesalers: Health Care'),
(8, 'CVS Health', 221751, 'United States', 'Woonsocket, RI', 'Health Care'),
(9, 'AmerisourceBergen', 208087, 'United States', 'Chesterbrook, PA', 'Wholesalers: Health Care'),
(10, 'AT&T', 181193, 'United States', 'Dallas, TX', 'Telecommunications'),
(11, 'Ford Motor', 160338, 'United States', 'Dearborn, MI', 'Motor Vehicles and Parts'),
(12, 'Chevron', 146516, 'United States', 'San Ramon, CA', 'Energy'),
(13, 'Cardinal Health', 145534, 'United States', 'Dublin, OH', 'Wholesalers: Health Care'),
(14, 'General Motors', 137237, 'United States', 'Detroit, MI', 'Motor Vehicles and Parts'),
(15, 'Walgreens Boots Alliance', 136866, 'United States', 'Deerfield, IL', 'Retailing'),
(16, 'Verizon Communications', 130863, 'United States', 'New York, NY', 'Telecommunications'),
(17, 'JP Morgan Chase', 118607, 'United States', 'New York, NY', 'Financials'),
(18, 'General Electric', 113093, 'United States', 'Boston, MA', 'Industrials'),
(19, 'Fannie Mae', 112394, 'United States', 'Washington, DC', 'Financials'),
(20, 'American Express', 111439, 'United States', 'New York, NY', 'Financials'),
(21, 'Wells Fargo', 110706, 'United States', 'San Francisco, CA', 'Financials'),
(22, 'Boeing', 101127, 'United States', 'Chicago, IL', 'Aerospace and Defense'),
(23, 'Phillips 66', 100515, 'United States', 'Houston, TX', 'Energy'),
(24, 'Citigroup', 97427, 'United States', 'New York, NY', 'Financials'),
(25, 'Cardinal Health', 92677, 'United States', 'Dublin, OH', 'Wholesalers: Health Care');


INSERT INTO customers (rank, company_name, revenue, country, address, industry) VALUES
(26, 'Home Depot', 88722, 'United States', 'Atlanta, GA', 'Retailing'),
(27, 'Comcast', 87134, 'United States', 'Philadelphia, PA', 'Telecommunications'),
(28, 'IBM', 77304, 'United States', 'Armonk, NY', 'Technology'),
(29, 'United Parcel Service', 74808, 'United States', 'Atlanta, GA', 'Transportation'),
(30, 'PepsiCo', 74385, 'United States', 'Purchase, NY', 'Food and Beverages'),
(31, 'Procter & Gamble', 71293, 'United States', 'Cincinnati, OH', 'Household Products'),
(32, 'Cisco Systems', 71519, 'United States', 'San Jose, CA', 'Technology'),
(33, 'Caterpillar', 68656, 'United States', 'Deerfield, IL', 'Industrials'),
(34, 'McDonald’s', 64517, 'United States', 'Chicago, IL', 'Hotels, Restaurants and Leisure'),
(35, 'The Coca-Cola Company', 63514, 'United States', 'Atlanta, GA', 'Food and Beverages'),
(36, 'Honeywell International', 62659, 'United States', 'Charlotte, NC', 'Industrials'),
(37, 'Dow', 61046, 'United States', 'Midland, MI', 'Chemicals'),
(38, 'State Farm Insurance', 60734, 'United States', 'Bloomington, IL', 'Insurance'),
(39, 'The Goldman Sachs Group', 59383, 'United States', 'New York, NY', 'Financials'),
(40, 'Humana', 56802, 'United States', 'Louisville, KY', 'Health Care'),
(41, 'Delta Air Lines', 56607, 'United States', 'Atlanta, GA', 'Transportation'),
(42, 'The Boeing Company', 58198, 'United States', 'Chicago, IL', 'Aerospace and Defense'),
(43, 'The Home Depot', 55984, 'United States', 'Atlanta, GA', 'Retailing'),
(44, 'The Travelers Companies', 55600, 'United States', 'New York, NY', 'Insurance'),
(45, 'American Airlines Group', 54599, 'United States', 'Fort Worth, TX', 'Transportation'),
(46, 'Cigna', 54031, 'United States', 'Bloomfield, CT', 'Health Care'),
(47, 'United Technologies', 53334, 'United States', 'Farmington, CT', 'Industrials'),
(48, 'PNC Financial Services', 52283, 'United States', 'Pittsburgh, PA', 'Financials'),
(49, 'The Southern Company', 51282, 'United States', 'Atlanta, GA', 'Energy'),
(50, 'Humana', 51212, 'United States', 'Louisville, KY', 'Health Care'),
(51, 'The Boeing Company', 50193, 'United States', 'Chicago, IL', 'Aerospace and Defense'),
(52, 'Lockheed Martin', 50039, 'United States', 'Bethesda, MD', 'Aerospace and Defense');


INSERT INTO customers (rank, company_name, revenue, country, address, industry) VALUES
(53, 'The Goldman Sachs Group', 43372, 'United States', 'New York, NY', 'Financials'),
(54, 'Morgan Stanley', 42656, 'United States', 'New York, NY', 'Financials'),
(55, 'The Dow Chemical Company', 42527, 'United States', 'Midland, MI', 'Chemicals'),
(56, 'The Progressive Corporation', 42416, 'United States', 'Mayfield Village, OH', 'Insurance'),
(57, 'The Chubb Corporation', 42304, 'United States', 'Zurich, Switzerland', 'Insurance'),
(58, 'Humana', 41878, 'United States', 'Louisville, KY', 'Health Care'),
(59, 'The Travelers Companies', 41502, 'United States', 'New York, NY', 'Insurance'),
(60, 'The Boeing Company', 40655, 'United States', 'Chicago, IL', 'Aerospace and Defense'),
(61, 'The Allstate Corporation', 40597, 'United States', 'Northfield Township, IL', 'Insurance'),
(62, 'The Procter & Gamble Company', 40141, 'United States', 'Cincinnati, OH', 'Household Products'),
(63, 'The Kraft Heinz Company', 39982, 'United States', 'Chicago, IL', 'Food and Beverages'),
(64, 'The Home Depot', 39727, 'United States', 'Atlanta, GA', 'Retailing'),
(65, 'The Hartford Financial Services Group', 38697, 'United States', 'Hartford, CT', 'Insurance'),
(66, 'The 3M Company', 38426, 'United States', 'St. Paul, MN', 'Industrials'),
(67, 'The Dow Chemical Company', 37737, 'United States', 'Midland, MI', 'Chemicals'),
(68, 'The Charles Schwab Corporation', 37583, 'United States', 'San Francisco, CA', 'Financials'),
(69, 'The United Parcel Service', 37543, 'United States', 'Atlanta, GA', 'Transportation'),
(70, 'The Goldman Sachs Group', 37513, 'United States', 'New York, NY', 'Financials'),
(71, 'The Aetna Corporation', 36746, 'United States', 'Hartford, CT', 'Health Care'),
(72, 'The Delta Air Lines', 36613, 'United States', 'Atlanta, GA', 'Transportation'),
(73, 'The Caterpillar Inc.', 36555, 'United States', 'Deerfield, IL', 'Industrials'),
(74, 'The DowDuPont Inc.', 35938, 'United States', 'Midland, MI', 'Chemicals'),
(75, 'The MetLife Inc.', 35624, 'United States', 'New York, NY', 'Insurance'),
(76, 'The United Technologies Corporation', 35568, 'United States', 'Farmington, CT', 'Industrials'),
(77, 'The Pfizer Inc.', 35369, 'United States', 'New York, NY', 'Pharmaceuticals'),
(78, 'The PNC Financial Services Group', 35213, 'United States', 'Pittsburgh, PA', 'Financials');

